export const route = {
  // home as new chat or thread
  home: '/',
  appLogs: '/logs',
  project: '/project',
  projectDetail: '/project/$projectId',
  artifacts: '/artifacts',
  security: '/security',
  knowledge: '/knowledge',
  automations: '/automations',
  review: '/review',
  wiki: '/wiki',
  integrations: '/integrations',
  activity: '/activity',
  sessions: '/sessions',
  environments: '/environments',
  agents: '/agents',
  playbooks: '/playbooks',
  teams: '/teams',
  billing: '/billing',
  usage: '/usage',
  members: '/members',
  apiKeys: '/api-keys',
  secrets: '/secrets',
  audit: '/audit',
  support: '/support',
  settingsMetric: '/settings/metric',
  settings: {
    index: '/settings',
    model_providers: '/settings/providers',
    providers: '/settings/providers/$providerName',
    general: '/settings/general',
    attachments: '/settings/attachments',
    interface: '/settings/interface',
    privacy: '/settings/privacy',
    shortcuts: '/settings/shortcuts',
    extensions: '/settings/extensions',
    local_api_server: '/settings/local-api-server',
    mcp_servers: '/settings/mcp-servers',
    https_proxy: '/settings/https-proxy',
    web_search: '/settings/web-search',
    hardware: '/settings/hardware',
    assistant: '/settings/assistant',
    claude_code: '/settings/claude-code',
  },
  hub: {
    index: '/hub/',
    model: '/hub/$modelId',
  },
  localApiServerlogs: '/local-api-server/logs',
  systemMonitor: '/system-monitor',
  threadsDetail: '/threads/$threadId',
}
