/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SystemMonitorRouteImport } from './routes/system-monitor'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads/$threadId'
import { Route as SettingsWebSearchRouteImport } from './routes/settings/web-search'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsMetricRouteImport } from './routes/settings/metric'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp-servers'
import { Route as SettingsLocalApiServerRouteImport } from './routes/settings/local-api-server'
import { Route as SettingsInterfaceRouteImport } from './routes/settings/interface'
import { Route as SettingsHttpsProxyRouteImport } from './routes/settings/https-proxy'
import { Route as SettingsHardwareRouteImport } from './routes/settings/hardware'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings/extensions'
import { Route as SettingsClaudeCodeRouteImport } from './routes/settings/claude-code'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsAssistantRouteImport } from './routes/settings/assistant'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as LocalApiServerLogsRouteImport } from './routes/local-api-server/logs'
import { Route as HubModelIdRouteImport } from './routes/hub/$modelId'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsProvidersProviderNameRouteImport } from './routes/settings/providers/$providerName'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMonitorRoute = SystemMonitorRouteImport.update({
  id: '/system-monitor',
  path: '/system-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebSearchRoute = SettingsWebSearchRouteImport.update({
  id: '/settings/web-search',
  path: '/settings/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMetricRoute = SettingsMetricRouteImport.update({
  id: '/settings/metric',
  path: '/settings/metric',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/settings/mcp-servers',
  path: '/settings/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLocalApiServerRoute = SettingsLocalApiServerRouteImport.update({
  id: '/settings/local-api-server',
  path: '/settings/local-api-server',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInterfaceRoute = SettingsInterfaceRouteImport.update({
  id: '/settings/interface',
  path: '/settings/interface',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHttpsProxyRoute = SettingsHttpsProxyRouteImport.update({
  id: '/settings/https-proxy',
  path: '/settings/https-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHardwareRoute = SettingsHardwareRouteImport.update({
  id: '/settings/hardware',
  path: '/settings/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/settings/extensions',
  path: '/settings/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsClaudeCodeRoute = SettingsClaudeCodeRouteImport.update({
  id: '/settings/claude-code',
  path: '/settings/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/settings/attachments',
  path: '/settings/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/settings/assistant',
  path: '/settings/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalApiServerLogsRoute = LocalApiServerLogsRouteImport.update({
  id: '/local-api-server/logs',
  path: '/local-api-server/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubModelIdRoute = HubModelIdRouteImport.update({
  id: '/hub/$modelId',
  path: '/hub/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/settings/providers/',
  path: '/settings/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersProviderNameRoute =
  SettingsProvidersProviderNameRouteImport.update({
    id: '/settings/providers/$providerName',
    path: '/settings/providers/$providerName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/billing': typeof BillingRoute
  '/environments': typeof EnvironmentsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/members': typeof MembersRoute
  '/playbooks': typeof PlaybooksRoute
  '/review': typeof ReviewRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/teams': typeof TeamsRoute
  '/usage': typeof UsageRoute
  '/wiki': typeof WikiRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/metric': typeof SettingsMetricRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/billing': typeof BillingRoute
  '/environments': typeof EnvironmentsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/members': typeof MembersRoute
  '/playbooks': typeof PlaybooksRoute
  '/review': typeof ReviewRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/teams': typeof TeamsRoute
  '/usage': typeof UsageRoute
  '/wiki': typeof WikiRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/metric': typeof SettingsMetricRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub': typeof HubIndexRoute
  '/project': typeof ProjectIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/billing': typeof BillingRoute
  '/environments': typeof EnvironmentsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/members': typeof MembersRoute
  '/playbooks': typeof PlaybooksRoute
  '/review': typeof ReviewRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/teams': typeof TeamsRoute
  '/usage': typeof UsageRoute
  '/wiki': typeof WikiRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/metric': typeof SettingsMetricRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agents'
    | '/api-keys'
    | '/artifacts'
    | '/audit'
    | '/automations'
    | '/billing'
    | '/environments'
    | '/integrations'
    | '/knowledge'
    | '/logs'
    | '/members'
    | '/playbooks'
    | '/review'
    | '/secrets'
    | '/security'
    | '/sessions'
    | '/support'
    | '/system-monitor'
    | '/teams'
    | '/usage'
    | '/wiki'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/metric'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/hub/'
    | '/project/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agents'
    | '/api-keys'
    | '/artifacts'
    | '/audit'
    | '/automations'
    | '/billing'
    | '/environments'
    | '/integrations'
    | '/knowledge'
    | '/logs'
    | '/members'
    | '/playbooks'
    | '/review'
    | '/secrets'
    | '/security'
    | '/sessions'
    | '/support'
    | '/system-monitor'
    | '/teams'
    | '/usage'
    | '/wiki'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/metric'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/hub'
    | '/project'
    | '/settings/providers/$providerName'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agents'
    | '/api-keys'
    | '/artifacts'
    | '/audit'
    | '/automations'
    | '/billing'
    | '/environments'
    | '/integrations'
    | '/knowledge'
    | '/logs'
    | '/members'
    | '/playbooks'
    | '/review'
    | '/secrets'
    | '/security'
    | '/sessions'
    | '/support'
    | '/system-monitor'
    | '/teams'
    | '/usage'
    | '/wiki'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/metric'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/hub/'
    | '/project/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentsRoute: typeof AgentsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ArtifactsRoute: typeof ArtifactsRoute
  AuditRoute: typeof AuditRoute
  AutomationsRoute: typeof AutomationsRoute
  BillingRoute: typeof BillingRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LogsRoute: typeof LogsRoute
  MembersRoute: typeof MembersRoute
  PlaybooksRoute: typeof PlaybooksRoute
  ReviewRoute: typeof ReviewRoute
  SecretsRoute: typeof SecretsRoute
  SecurityRoute: typeof SecurityRoute
  SessionsRoute: typeof SessionsRoute
  SupportRoute: typeof SupportRoute
  SystemMonitorRoute: typeof SystemMonitorRoute
  TeamsRoute: typeof TeamsRoute
  UsageRoute: typeof UsageRoute
  WikiRoute: typeof WikiRoute
  HubModelIdRoute: typeof HubModelIdRoute
  LocalApiServerLogsRoute: typeof LocalApiServerLogsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsClaudeCodeRoute: typeof SettingsClaudeCodeRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHardwareRoute: typeof SettingsHardwareRoute
  SettingsHttpsProxyRoute: typeof SettingsHttpsProxyRoute
  SettingsInterfaceRoute: typeof SettingsInterfaceRoute
  SettingsLocalApiServerRoute: typeof SettingsLocalApiServerRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsMetricRoute: typeof SettingsMetricRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsWebSearchRoute: typeof SettingsWebSearchRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  HubIndexRoute: typeof HubIndexRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  SettingsProvidersProviderNameRoute: typeof SettingsProvidersProviderNameRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-monitor': {
      id: '/system-monitor'
      path: '/system-monitor'
      fullPath: '/system-monitor'
      preLoaderRoute: typeof SystemMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/web-search': {
      id: '/settings/web-search'
      path: '/settings/web-search'
      fullPath: '/settings/web-search'
      preLoaderRoute: typeof SettingsWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/metric': {
      id: '/settings/metric'
      path: '/settings/metric'
      fullPath: '/settings/metric'
      preLoaderRoute: typeof SettingsMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp-servers': {
      id: '/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/local-api-server': {
      id: '/settings/local-api-server'
      path: '/settings/local-api-server'
      fullPath: '/settings/local-api-server'
      preLoaderRoute: typeof SettingsLocalApiServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/interface': {
      id: '/settings/interface'
      path: '/settings/interface'
      fullPath: '/settings/interface'
      preLoaderRoute: typeof SettingsInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/https-proxy': {
      id: '/settings/https-proxy'
      path: '/settings/https-proxy'
      fullPath: '/settings/https-proxy'
      preLoaderRoute: typeof SettingsHttpsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hardware': {
      id: '/settings/hardware'
      path: '/settings/hardware'
      fullPath: '/settings/hardware'
      preLoaderRoute: typeof SettingsHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/settings/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/claude-code': {
      id: '/settings/claude-code'
      path: '/settings/claude-code'
      fullPath: '/settings/claude-code'
      preLoaderRoute: typeof SettingsClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/settings/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/settings/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-api-server/logs': {
      id: '/local-api-server/logs'
      path: '/local-api-server/logs'
      fullPath: '/local-api-server/logs'
      preLoaderRoute: typeof LocalApiServerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$modelId': {
      id: '/hub/$modelId'
      path: '/hub/$modelId'
      fullPath: '/hub/$modelId'
      preLoaderRoute: typeof HubModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/settings/providers'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/$providerName': {
      id: '/settings/providers/$providerName'
      path: '/settings/providers/$providerName'
      fullPath: '/settings/providers/$providerName'
      preLoaderRoute: typeof SettingsProvidersProviderNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentsRoute: AgentsRoute,
  ApiKeysRoute: ApiKeysRoute,
  ArtifactsRoute: ArtifactsRoute,
  AuditRoute: AuditRoute,
  AutomationsRoute: AutomationsRoute,
  BillingRoute: BillingRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LogsRoute: LogsRoute,
  MembersRoute: MembersRoute,
  PlaybooksRoute: PlaybooksRoute,
  ReviewRoute: ReviewRoute,
  SecretsRoute: SecretsRoute,
  SecurityRoute: SecurityRoute,
  SessionsRoute: SessionsRoute,
  SupportRoute: SupportRoute,
  SystemMonitorRoute: SystemMonitorRoute,
  TeamsRoute: TeamsRoute,
  UsageRoute: UsageRoute,
  WikiRoute: WikiRoute,
  HubModelIdRoute: HubModelIdRoute,
  LocalApiServerLogsRoute: LocalApiServerLogsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsClaudeCodeRoute: SettingsClaudeCodeRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHardwareRoute: SettingsHardwareRoute,
  SettingsHttpsProxyRoute: SettingsHttpsProxyRoute,
  SettingsInterfaceRoute: SettingsInterfaceRoute,
  SettingsLocalApiServerRoute: SettingsLocalApiServerRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsMetricRoute: SettingsMetricRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsWebSearchRoute: SettingsWebSearchRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  HubIndexRoute: HubIndexRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  SettingsProvidersProviderNameRoute: SettingsProvidersProviderNameRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
