/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as VariablesRouteImport } from './routes/variables'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SystemMonitorRouteImport } from './routes/system-monitor'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GithubRouteImport } from './routes/github'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads/$threadId'
import { Route as SettingsWebSearchRouteImport } from './routes/settings/web-search'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsMetricRouteImport } from './routes/settings/metric'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp-servers'
import { Route as SettingsLocalApiServerRouteImport } from './routes/settings/local-api-server'
import { Route as SettingsInterfaceRouteImport } from './routes/settings/interface'
import { Route as SettingsHttpsProxyRouteImport } from './routes/settings/https-proxy'
import { Route as SettingsHardwareRouteImport } from './routes/settings/hardware'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings/extensions'
import { Route as SettingsClaudeCodeRouteImport } from './routes/settings/claude-code'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsAssistantRouteImport } from './routes/settings/assistant'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as LocalApiServerLogsRouteImport } from './routes/local-api-server/logs'
import { Route as HubModelIdRouteImport } from './routes/hub/$modelId'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsProvidersProviderNameRouteImport } from './routes/settings/providers/$providerName'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMonitorRoute = SystemMonitorRouteImport.update({
  id: '/system-monitor',
  path: '/system-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebSearchRoute = SettingsWebSearchRouteImport.update({
  id: '/settings/web-search',
  path: '/settings/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMetricRoute = SettingsMetricRouteImport.update({
  id: '/settings/metric',
  path: '/settings/metric',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/settings/mcp-servers',
  path: '/settings/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLocalApiServerRoute = SettingsLocalApiServerRouteImport.update({
  id: '/settings/local-api-server',
  path: '/settings/local-api-server',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInterfaceRoute = SettingsInterfaceRouteImport.update({
  id: '/settings/interface',
  path: '/settings/interface',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHttpsProxyRoute = SettingsHttpsProxyRouteImport.update({
  id: '/settings/https-proxy',
  path: '/settings/https-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHardwareRoute = SettingsHardwareRouteImport.update({
  id: '/settings/hardware',
  path: '/settings/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/settings/extensions',
  path: '/settings/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsClaudeCodeRoute = SettingsClaudeCodeRouteImport.update({
  id: '/settings/claude-code',
  path: '/settings/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/settings/attachments',
  path: '/settings/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/settings/assistant',
  path: '/settings/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalApiServerLogsRoute = LocalApiServerLogsRouteImport.update({
  id: '/local-api-server/logs',
  path: '/local-api-server/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubModelIdRoute = HubModelIdRouteImport.update({
  id: '/hub/$modelId',
  path: '/hub/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/settings/providers/',
  path: '/settings/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersProviderNameRoute =
  SettingsProvidersProviderNameRouteImport.update({
    id: '/settings/providers/$providerName',
    path: '/settings/providers/$providerName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/billing': typeof BillingRoute
  '/command-center': typeof CommandCenterRoute
  '/connections': typeof ConnectionsRoute
  '/deployments': typeof DeploymentsRoute
  '/documents': typeof DocumentsRoute
  '/environments': typeof EnvironmentsRoute
  '/github': typeof GithubRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRoute
  '/members': typeof MembersRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/playbooks': typeof PlaybooksRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/storage': typeof StorageRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/variables': typeof VariablesRoute
  '/wiki': typeof WikiRoute
  '/workspace': typeof WorkspaceRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/metric': typeof SettingsMetricRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/billing': typeof BillingRoute
  '/command-center': typeof CommandCenterRoute
  '/connections': typeof ConnectionsRoute
  '/deployments': typeof DeploymentsRoute
  '/documents': typeof DocumentsRoute
  '/environments': typeof EnvironmentsRoute
  '/github': typeof GithubRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRoute
  '/members': typeof MembersRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/playbooks': typeof PlaybooksRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/storage': typeof StorageRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/variables': typeof VariablesRoute
  '/wiki': typeof WikiRoute
  '/workspace': typeof WorkspaceRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/metric': typeof SettingsMetricRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub': typeof HubIndexRoute
  '/project': typeof ProjectIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/billing': typeof BillingRoute
  '/command-center': typeof CommandCenterRoute
  '/connections': typeof ConnectionsRoute
  '/deployments': typeof DeploymentsRoute
  '/documents': typeof DocumentsRoute
  '/environments': typeof EnvironmentsRoute
  '/github': typeof GithubRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRoute
  '/members': typeof MembersRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/playbooks': typeof PlaybooksRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/secrets': typeof SecretsRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/storage': typeof StorageRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/variables': typeof VariablesRoute
  '/wiki': typeof WikiRoute
  '/workspace': typeof WorkspaceRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/local-api-server/logs': typeof LocalApiServerLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/local-api-server': typeof SettingsLocalApiServerRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/metric': typeof SettingsMetricRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/api-keys'
    | '/artifacts'
    | '/audit'
    | '/automations'
    | '/billing'
    | '/command-center'
    | '/connections'
    | '/deployments'
    | '/documents'
    | '/environments'
    | '/github'
    | '/history'
    | '/integrations'
    | '/knowledge'
    | '/logs'
    | '/marketplace'
    | '/members'
    | '/memory'
    | '/models'
    | '/monitoring'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/playbooks'
    | '/plugins'
    | '/profile'
    | '/reports'
    | '/review'
    | '/secrets'
    | '/security'
    | '/sessions'
    | '/storage'
    | '/support'
    | '/system-monitor'
    | '/tasks'
    | '/teams'
    | '/templates'
    | '/terminal'
    | '/usage'
    | '/variables'
    | '/wiki'
    | '/workspace'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/metric'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/hub/'
    | '/project/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/api-keys'
    | '/artifacts'
    | '/audit'
    | '/automations'
    | '/billing'
    | '/command-center'
    | '/connections'
    | '/deployments'
    | '/documents'
    | '/environments'
    | '/github'
    | '/history'
    | '/integrations'
    | '/knowledge'
    | '/logs'
    | '/marketplace'
    | '/members'
    | '/memory'
    | '/models'
    | '/monitoring'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/playbooks'
    | '/plugins'
    | '/profile'
    | '/reports'
    | '/review'
    | '/secrets'
    | '/security'
    | '/sessions'
    | '/storage'
    | '/support'
    | '/system-monitor'
    | '/tasks'
    | '/teams'
    | '/templates'
    | '/terminal'
    | '/usage'
    | '/variables'
    | '/wiki'
    | '/workspace'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/metric'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/hub'
    | '/project'
    | '/settings/providers/$providerName'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agents'
    | '/analytics'
    | '/api'
    | '/api-keys'
    | '/artifacts'
    | '/audit'
    | '/automations'
    | '/billing'
    | '/command-center'
    | '/connections'
    | '/deployments'
    | '/documents'
    | '/environments'
    | '/github'
    | '/history'
    | '/integrations'
    | '/knowledge'
    | '/logs'
    | '/marketplace'
    | '/members'
    | '/memory'
    | '/models'
    | '/monitoring'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/playbooks'
    | '/plugins'
    | '/profile'
    | '/reports'
    | '/review'
    | '/secrets'
    | '/security'
    | '/sessions'
    | '/storage'
    | '/support'
    | '/system-monitor'
    | '/tasks'
    | '/teams'
    | '/templates'
    | '/terminal'
    | '/usage'
    | '/variables'
    | '/wiki'
    | '/workspace'
    | '/hub/$modelId'
    | '/local-api-server/logs'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/attachments'
    | '/settings/claude-code'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/hardware'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/local-api-server'
    | '/settings/mcp-servers'
    | '/settings/metric'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/hub/'
    | '/project/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiRoute: typeof ApiRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ArtifactsRoute: typeof ArtifactsRoute
  AuditRoute: typeof AuditRoute
  AutomationsRoute: typeof AutomationsRoute
  BillingRoute: typeof BillingRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DeploymentsRoute: typeof DeploymentsRoute
  DocumentsRoute: typeof DocumentsRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  GithubRoute: typeof GithubRoute
  HistoryRoute: typeof HistoryRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LogsRoute: typeof LogsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MembersRoute: typeof MembersRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  MonitoringRoute: typeof MonitoringRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationRoute: typeof OrganizationRoute
  PermissionsRoute: typeof PermissionsRoute
  PlaybooksRoute: typeof PlaybooksRoute
  PluginsRoute: typeof PluginsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SecretsRoute: typeof SecretsRoute
  SecurityRoute: typeof SecurityRoute
  SessionsRoute: typeof SessionsRoute
  StorageRoute: typeof StorageRoute
  SupportRoute: typeof SupportRoute
  SystemMonitorRoute: typeof SystemMonitorRoute
  TasksRoute: typeof TasksRoute
  TeamsRoute: typeof TeamsRoute
  TemplatesRoute: typeof TemplatesRoute
  TerminalRoute: typeof TerminalRoute
  UsageRoute: typeof UsageRoute
  VariablesRoute: typeof VariablesRoute
  WikiRoute: typeof WikiRoute
  WorkspaceRoute: typeof WorkspaceRoute
  HubModelIdRoute: typeof HubModelIdRoute
  LocalApiServerLogsRoute: typeof LocalApiServerLogsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsClaudeCodeRoute: typeof SettingsClaudeCodeRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHardwareRoute: typeof SettingsHardwareRoute
  SettingsHttpsProxyRoute: typeof SettingsHttpsProxyRoute
  SettingsInterfaceRoute: typeof SettingsInterfaceRoute
  SettingsLocalApiServerRoute: typeof SettingsLocalApiServerRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsMetricRoute: typeof SettingsMetricRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsWebSearchRoute: typeof SettingsWebSearchRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  HubIndexRoute: typeof HubIndexRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  SettingsProvidersProviderNameRoute: typeof SettingsProvidersProviderNameRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-monitor': {
      id: '/system-monitor'
      path: '/system-monitor'
      fullPath: '/system-monitor'
      preLoaderRoute: typeof SystemMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/web-search': {
      id: '/settings/web-search'
      path: '/settings/web-search'
      fullPath: '/settings/web-search'
      preLoaderRoute: typeof SettingsWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/metric': {
      id: '/settings/metric'
      path: '/settings/metric'
      fullPath: '/settings/metric'
      preLoaderRoute: typeof SettingsMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp-servers': {
      id: '/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/local-api-server': {
      id: '/settings/local-api-server'
      path: '/settings/local-api-server'
      fullPath: '/settings/local-api-server'
      preLoaderRoute: typeof SettingsLocalApiServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/interface': {
      id: '/settings/interface'
      path: '/settings/interface'
      fullPath: '/settings/interface'
      preLoaderRoute: typeof SettingsInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/https-proxy': {
      id: '/settings/https-proxy'
      path: '/settings/https-proxy'
      fullPath: '/settings/https-proxy'
      preLoaderRoute: typeof SettingsHttpsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hardware': {
      id: '/settings/hardware'
      path: '/settings/hardware'
      fullPath: '/settings/hardware'
      preLoaderRoute: typeof SettingsHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/settings/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/claude-code': {
      id: '/settings/claude-code'
      path: '/settings/claude-code'
      fullPath: '/settings/claude-code'
      preLoaderRoute: typeof SettingsClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/settings/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/settings/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-api-server/logs': {
      id: '/local-api-server/logs'
      path: '/local-api-server/logs'
      fullPath: '/local-api-server/logs'
      preLoaderRoute: typeof LocalApiServerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$modelId': {
      id: '/hub/$modelId'
      path: '/hub/$modelId'
      fullPath: '/hub/$modelId'
      preLoaderRoute: typeof HubModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/settings/providers'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/$providerName': {
      id: '/settings/providers/$providerName'
      path: '/settings/providers/$providerName'
      fullPath: '/settings/providers/$providerName'
      preLoaderRoute: typeof SettingsProvidersProviderNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiRoute: ApiRoute,
  ApiKeysRoute: ApiKeysRoute,
  ArtifactsRoute: ArtifactsRoute,
  AuditRoute: AuditRoute,
  AutomationsRoute: AutomationsRoute,
  BillingRoute: BillingRoute,
  CommandCenterRoute: CommandCenterRoute,
  ConnectionsRoute: ConnectionsRoute,
  DeploymentsRoute: DeploymentsRoute,
  DocumentsRoute: DocumentsRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  GithubRoute: GithubRoute,
  HistoryRoute: HistoryRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LogsRoute: LogsRoute,
  MarketplaceRoute: MarketplaceRoute,
  MembersRoute: MembersRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  MonitoringRoute: MonitoringRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationRoute: OrganizationRoute,
  PermissionsRoute: PermissionsRoute,
  PlaybooksRoute: PlaybooksRoute,
  PluginsRoute: PluginsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SecretsRoute: SecretsRoute,
  SecurityRoute: SecurityRoute,
  SessionsRoute: SessionsRoute,
  StorageRoute: StorageRoute,
  SupportRoute: SupportRoute,
  SystemMonitorRoute: SystemMonitorRoute,
  TasksRoute: TasksRoute,
  TeamsRoute: TeamsRoute,
  TemplatesRoute: TemplatesRoute,
  TerminalRoute: TerminalRoute,
  UsageRoute: UsageRoute,
  VariablesRoute: VariablesRoute,
  WikiRoute: WikiRoute,
  WorkspaceRoute: WorkspaceRoute,
  HubModelIdRoute: HubModelIdRoute,
  LocalApiServerLogsRoute: LocalApiServerLogsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsClaudeCodeRoute: SettingsClaudeCodeRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHardwareRoute: SettingsHardwareRoute,
  SettingsHttpsProxyRoute: SettingsHttpsProxyRoute,
  SettingsInterfaceRoute: SettingsInterfaceRoute,
  SettingsLocalApiServerRoute: SettingsLocalApiServerRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsMetricRoute: SettingsMetricRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsWebSearchRoute: SettingsWebSearchRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  HubIndexRoute: HubIndexRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  SettingsProvidersProviderNameRoute: SettingsProvidersProviderNameRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
